from setuptools import setup, find_packages

setup(
    name="fvbio",
    version="0.1.0",
    description="Face Verification Biometric Research: Classical vs. Deep, Cross-Domain Robustness",
    author="Mojgan Hosseini",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.9",
    install_requires=[
        "torch>=2.0",
        "torchvision>=0.15",
        "facenet-pytorch>=2.5",
        "insightface>=0.7",
        "onnxruntime>=1.16",
        "scikit-learn>=1.3",
        "scikit-image>=0.21",
        "opencv-python>=4.8",
        "Pillow>=10.0",
        "numpy>=1.24",
        "scipy>=1.11",
        "pandas>=2.0",
        "matplotlib>=3.7",
        "seaborn>=0.12",
        "PyYAML>=6.0",
        "gradio>=4.0",
        "tqdm>=4.65",
        "requests>=2.31",
    ],
)
